// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp6__lRdagJZ4IpTlGkY3rz5iSSk511xI',
    appId: '1:917992327675:web:e1ba38bafde4b31dfae35e',
    messagingSenderId: '917992327675',
    projectId: 'scamscribezx',
    authDomain: 'scamscribezx.firebaseapp.com',
    storageBucket: 'scamscribezx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAkH99Gg84CSyoWvwKXgKcMDmLnZhksNA',
    appId: '1:917992327675:android:c254122b34307ea6fae35e',
    messagingSenderId: '917992327675',
    projectId: 'scamscribezx',
    storageBucket: 'scamscribezx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgXpS5xpplS7_adbl9WUV1JtIZntNTjw',
    appId: '1:917992327675:ios:d5bcbf09d7c7e247fae35e',
    messagingSenderId: '917992327675',
    projectId: 'scamscribezx',
    storageBucket: 'scamscribezx.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
